### ISSUE TITLE
Password prompt doesn't work under cygwin

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cli#347]
I imagine cygwin support is almost nowhere in the project's roadmap.  But thought I'd inform the project that the login password prompt doesn't work under cygwin in case you are interested in fixing it. :)

```
$ cf login -u youngm
API endpoint: https://api.cf.somedomain.org
Authenticating...
Credentials were rejected, please try again.
Authenticating...
Credentials were rejected, please try again.
Authenticating...
Credentials were rejected, please try again.
FAILED
Unable to authenticate.
```

In the example above I'm never prompted for a password.

**Comment by camelpunch** [comment]
Hey @youngm! We're trying to catch up with older issues. Do you know if this is still a problem under Cygwin?

**Comment by youngm** [comment]
@camelpunch I will find out.

**Comment by youngm** [comment]
@camelpunch yes.  My users have confirmed that this is still an issue as of 6.12.3

**Comment by camelpunch** [comment]
Thanks!

**Comment by camelpunch** [comment]
@goehmen fair to call this a wontfix? I think @squeedee and @simonleung8 came to a conclusion in the last retro that Powershell was the thing to support, since it sorta covers cmd.exe too.

**Comment by youngm** [comment]
@camelpunch FWIW, most of my users like cygwin because of the ansi color support.

**Comment by youngm** [comment]
@camelpunch Another use case I've heard is teams with mixed workstation types will sometimes script environment setup using bash.  Windows users will use cygwin to execute those bash scripts so they don't need to write separate .bat scripts for windows users.

**Comment by dkoper** [comment]
Thanks for the feedback on ansi colour support on Windows, we have a story on that. Hearing that people resort to cygwin because it's not there yet helps prioritize it.

To go back to your issue, trying on my Windows 7 machine it worked fine. Possibly we fixed something in the latest cf release that fixed it?

```
D:\projects\cf\>cf --version
cf version 6.13.0-e68ce0f-2015-10-15T15:53:50+00:00
D:\projects\cf\>bash --version
GNU bash, version 4.3.33(1)-release (x86_64-unknown-cygwin)
...
D:\projects\cf\>bash
KOPERD@ONE7-FAS200007 /cygdrive/d/projects/cf
$ cf login -u admin
API endpoint: https://api....

Password>
Authenticating...
OK

Select an org (or press enter to skip):
...
```

**Comment by youngm** [comment]
@dkoper Interesting.  I'll see if my windows guys are still having issues with 6.13.0.

**Comment by youngm** [comment]
@dkoper So executing bash from a regular windows command prompt does allow you to login but ANSI color does not work.  So this would work for the shell script use case.

But, if you try to login from a cygwin terminal where ANSI color does work then login fails.

**Comment by krishicks** [comment]
@youngm: You're right, we don't have cygwin on the roadmap. You can see it here: https://www.pivotaltracker.com/n/projects/892938

I'll close this for now as if we do decide to support cygwin it'd be more than a bug; it'd probably be a series of stories.

**Comment by youngm** [comment]
@krishicks understandable.  This issue is a small one and there are workarounds.  However, I think the ability to share shell scripts between platforms is an important one which is working now.  I hope you'll at least consider cygwin issues related to scripting without workarounds in the future to keep cross platform script sharing possible.

**Comment by dkoper** [comment]
If there are many cygwin users running into issues I'm sure they'll come across this conversation at some point. I'd like to recommend them to keep reporting their issues here in the GH tracker or on the mailing list - that will help us prioritize cygwin support appropriately.

**Comment by youngm** [comment]
@dkoper sounds reasonable.  I guess we'll see how things go.  Thanks.

**Comment by dkoper** [comment]
Hi @youngm 

FYI, although the initial bug description looks different, you raised the same as in #171, which I have reopened to at least explore what's involved.

Regards,
Dies Koper
CF CLI PM
